apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
    - name: api
      protocol: TCP
      port: 7777
      targetPort: api
      nodePort: 37777
    - name: game
      protocol: UDP
      port: 7777
      targetPort: game
      nodePort: 37777
  selector:
    app: satisfactory
