apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-application
  namespace: argocd
spec:
  project: default

  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: "25.30.0"
    helm:
      valueFiles:
        - $kubernetes_homeNodes/argo/prometheus/values.yaml

  - repoURL: https://github.com/Liscano12/kubernetes_homeNodes.git
    targetRevision: main
    ref: kubernetes_homeNodes

  destination: 
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
